import unittest

class TestDirector(unittest.TestCase):

	def test_1(self):
		import compy
	def test_2(self):
		import compy.actor
	def test_3(self):
		import compy.director
	def test_4(self):
		import compy.errors
	def test_5(self):
		import compy.event
	def test_6(self):
		import compy.logger
	def test_7(self):
		import compy.queue
	def test_8(self):
		import compy.restartlet
	def test_9(self):
		import compy.actors
	def test_10(self):
		import compy.mixins
	def test_11(self):
		import compy.actors.auth
	def test_12(self):
		import compy.actors.database
	def test_13(self):
		import compy.actors.eventgenerator
	def test_14(self):
		import compy.actors.eventjoin
	def test_15(self):
		import compy.actors.eventlogger
	def test_16(self):
		import compy.actors.eventrouter
	def test_17(self):
		import compy.actors.filelogger
	def test_18(self):
		import compy.actors.flowcontroller
	def test_19(self):
		import compy.actors.httpserver
	def test_20(self):
		import compy.actors.jsonvalidator
	def test_21(self):
		import compy.actors.mdpactors
	def test_22(self):
		import compy.actors.mdpbroker
	def test_23(self):
		import compy.actors.mdpregistrar
	def test_24(self):
		import compy.actors.middleware
	def test_25(self):
		import compy.actors.modifier_definitions
	def test_26(self):
		import compy.actors.modifiers
	def test_27(self):
		import compy.actors.mysql
	def test_28(self):
		import compy.actors.null
	def test_29(self):
		import compy.actors.stdout
	def test_30(self):
		import compy.actors.xsd
	def test_31(self):
		import compy.actors.xslt
	def test_32(self):
		import compy.actors.zeromq
	def test_33(self):
		import compy.actors.mixins.auth
	def test_34(self):
		import compy.actors.mixins.database
	def test_35(self):
		import compy.mixins.event
	def test_36(self):
		import compy.actors.mixins.interpretor
	def test_38(self):
		import compy.actors.mixins.modifiers

